name: Test packaging and installing

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'Dockerfile'
      - '.github/workflows/docker_publish.yml'
      - 'environment.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: set up python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}       
      - run: conda install conda-build 
      - run: conda develop .
        name: Install locally with conda
      - name: Install with pip
        run: pip install .[develop]
      - name: Test building wheels
        run: python -m build --sdist --wheel
